# Build environment and configuration documentation:
# http://docs.travis-ci.com/user/languages/php/
sudo: false
language: php
os:
  - linux
php:
  - 7.2
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
branches:
  except:
    - /^psr.*$/
    - /^dev.*$/
    - /^topic.*$/
install: composer install --dev
script: phpunit
notifications:
  email: false
